version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - .env

  pgbouncer:
    image: edoburu/pgbouncer
    restart: always
    container_name: pgbouncer
    env_file:
      - .env
    ports:
      - "5432:5432"
    depends_on:
      - postgres

  web:
#    image: anywindblows/app_notes:latest
    build:
      context: ../
      dockerfile: app_notes/Dockerfile
    restart: always
    container_name: web
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: "gunicorn config.wsgi:application --bind 0:8000"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - pgbouncer

  nginx:
    image: nginx:1.23.2-alpine
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  postgres_value:
  static_value:
  media_value:
