name: "Auto Assign"
on:
  pull_request:
    types: [assigned]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-assignee@v1.1.0
      with:
        config: '.github/assignee.config.yml'
        token: ${{ secrets.GITHUB_TOKEN }}

